spring:
  jpa:
    hibernate:
         ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    username: root
    password: root

jwt:
  private:
    key: <secret>




